spring.application.name=CoffeeCAppUnipa
spring.datasource.url=jdbc:mariadb://localhost:3306/coffeecappunipa?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=drowssap

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Session Configuration
spring.session.jdbc.initialize-schema=always
server.servlet.session.timeout=30m